spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: setsdev
    password: sets001
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true