--TO DELETE QUICKLY
EXEC POPULATE_TEAM;

EXEC POPULATE_PLAYER;

--TO DELETE QUICKLY
DELETE FROM TEAM WHERE ROWNUM < 50000;
COMMIT;

DELETE FROM PLAYER WHERE ROWNUM < 100000;
COMMIT;


/*
DROP TABLE cached_lookup_tab;

CREATE TABLE cached_lookup_tab (
    NUMERO  NUMBER(9),
    id      CHAR(36)  NOT NULL
);

ALTER TABLE cached_lookup_tab ADD (
  CONSTRAINT cached_lookup_tab_pk
  PRIMARY KEY (NUMERO)
);

INSERT INTO cached_lookup_tab (NUMERO, ID)
SELECT ROWNUM, ID FROM TEAM;
/
*/



